add errors/unmatched rules in the rulesets
konveyor/analyzer-lsp pull request #114
Opened 2023-04-10 19:44 UTC by pranavgaikwad

2023-04-26 15:55 UTC, fabianvf requested changes

2023-04-26 15:55 UTC, fabianvf commented on analyzer-lsp-main
I think you committed this binary accidentally, we should remove it from this PR and probably add it to the .gitignore as well

2023-04-27 19:11 UTC, pranavgaikwad commented on hubapi/violations.go
> +	Errors map[string]string `yaml:"errors,omitempty"`
Not right now

2023-05-02 13:01 UTC, shawn-hurley approved these changes
I think this is an excellent first step I do think that we are going to need to update the API everywhere :)

2023-05-02 14:57 UTC, pranavgaikwad commented
Following up on multiple errors thing in issue here https://github.com/konveyor/analyzer-lsp/issues/133

2023-05-02 15:03 UTC, merged