Adding engine configuration pattern and config for limits on incidents
konveyor/analyzer-lsp pull request #157
Opened 2023-05-16 19:36 UTC by shawn-hurley

fixes #153 
fixes #154

2023-05-17 13:57 UTC, pranavgaikwad requested changes
Requesting variable rename, rest all looks good

2023-05-17 13:57 UTC, pranavgaikwad commented on engine/engine.go
> +	codeSnipeLimit int
nit: `/codeSnipeLimit/codeSnipLimit/`

2023-05-18 15:38 UTC, shawn-hurley commented on engine/engine.go
> +	codeSnipeLimit int
updated

2023-05-18 16:13 UTC, pranavgaikwad approved these changes

2023-05-18 16:13 UTC, merged