WIP pulling line number out of variables in incident struct
konveyor/analyzer-lsp pull request #195
Opened 2023-06-05 19:17 UTC by Chanakya-TS

fixes #186

2023-06-05 19:30 UTC, Chanakya-TS commented
currently, i am pulling the line number out of variables and putting it separately in the incident. im not sure if this is what is required. i may have to query the provider the line number and pipe it through for every incident but i am not sure how to do that. 

i also need to figure out how to make sure that the {{lineNumber}} in rules message takes the line number which is now outside the variables.

2023-06-06 15:45 UTC, shawn-hurley requested changes
Good start, but I think that you can go even further down the stack and force the providers to choose. 

Also a minor comment on the API. 

This is a really good start though!

2023-06-06 15:45 UTC, shawn-hurley commented on engine/engine.go
> +		lineNumber, hasLineNumber := m.Variables["lineNumber"]
I think that is reasonable to update the contract of the providers to include this as a top level. I would look 
https://github.com/konveyor/analyzer-lsp/blob/main/provider/provider.go#L117 to start.

2023-06-07 19:14 UTC, shawn-hurley commented
I would mark this reviewable and i would update the demo-output but otherwise this looks good. Sonds like the pointer will be a followup. I am ok with it as long as it is a quick follow on. @Chanakya-TS can you create an issue and align it to Demo E?

2023-06-12 14:20 UTC, shawn-hurley approved these changes
This looks great! move it out of draft so we can merge!

2023-06-13 00:50 UTC, merged