Add XMLPublicid condition to builtin provider
konveyor/analyzer-lsp pull request #306
Opened 2023-08-25 08:48 UTC by aufi

Adding XML-like public-id condition supporting regular expression evaluation on the public-id attribute.

Related to https://github.com/konveyor/windup-shim/pull/87 Related to https://github.com/konveyor/analyzer-lsp/issues/221

2023-08-31 13:09 UTC, shawn-hurley commented
@aufi is this ready for review?

2023-09-14 21:07 UTC, shawn-hurley requested changes
I think that we should share the code for XML set up in a function, While you are there you can fix a bug and close the file for the original xml implementation.

2023-09-14 21:07 UTC, shawn-hurley commented on provider/internal/builtin/provider.go
> +	XMLPublicid              xmlPublicidCondition `yaml:"xmlPublicid"`
XMLPublicID is I think how it should be for this struct.

2023-09-14 21:07 UTC, shawn-hurley commented on provider/internal/builtin/provider.go
> +type xmlPublicidCondition struct {
same here xmlPublicIDCondition

2023-09-14 21:07 UTC, shawn-hurley commented on provider/internal/builtin/service_client.go
> +			f, err := os.Open(file)
make sure that we close this file

2023-11-22 15:08 UTC, aufi commented
Thanks for review&feedback @shawn-hurley, updated.

2023-11-22 15:18 UTC, aufi commented
The CI failure comes from missing update/merge of https://github.com/konveyor/go-konveyor-tests/pull/65. This PR will be merged when gets green, but I'd be grateful for review.

2023-11-30 10:32 UTC, aufi commented
@shawn-hurley @jmle Added demo rule for the xmlPublicID condition. Ready for review.

2023-12-12 13:22 UTC, aufi commented on provider/internal/builtin/service_client.go
> +func queryXMLFile(filePath string, query *xpath.Expr) (nodes []*xmlquery.Node, err error) {
Updated returns to use values directly (I didn't realize it is not used in analyzer in that way)

2023-12-12 13:48 UTC, merged