fix: exit after showing help
konveyor/analyzer-lsp pull request #468
Opened 2024-01-18 20:14 UTC by Vickysomtee

2024-01-19 16:49 UTC, pranavgaikwad requested changes
@Vickysomtee hey thank you for your fix. it should work! But I noticed that when we integrated cobra, we didn't do things quite the "cobra" way. Are you willing to help us refactor that code? The changes I am looking for are - 
1. main() function only calls cmd.Execute() The actual code that runs the analysis is removed from main()
2. analysis code goes into command's RunE() funcion instead 

Here's a good example of using different hooks in a cobra command: https://github.com/konveyor/kantra/blob/20af46fafa3876cd56f5b3be20610c7185673142/cmd/analyze.go#L85-L150

2024-01-19 21:31 UTC, Vickysomtee commented
> @Vickysomtee hey thank you for your fix. it should work! But I noticed that when we integrated cobra, we didn't do things quite the "cobra" way. Are you willing to help us refactor that code? The changes I am looking for are -
> 
> 1. main() function only calls cmd.Execute() The actual code that runs the analysis is removed from main()
> 2. analysis code goes into command's RunE() funcion instead
> 
> Here's a good example of using different hooks in a cobra command: https://github.com/konveyor/kantra/blob/20af46fafa3876cd56f5b3be20610c7185673142/cmd/analyze.go#L85-L150

@pranavgaikwad Yes, I  would love to refactor this. Few questions though

1. Can I continue this refactor in this same PR?
2. Can you help highlight the code that handles the analysis so I can go through it and understand it better.
3. Are we writing tests for this? Additional context will be appreciated

2024-01-19 21:44 UTC, shawn-hurley commented
> 1. Can I continue this refactor in this same PR?

Yeah absolutely

> 2. Can you help highlight the code that handles the analysis so I can go through it and understand it better.

https://github.com/konveyor/analyzer-lsp/blob/main/cmd/analyzer/main.go#L201

This is where the engine runs the rules, but all the setup is also very important

https://github.com/konveyor/analyzer-lsp/blob/main/cmd/analyzer/main.go#L96-L199

The important parts here are rule parsing and getting and setting up the correct providers.

> 3. Are we writing tests for this? Additional context will be appreciated.

No test will be needed for this refactor, our e2e tests will test this!

2024-01-19 21:48 UTC, Vickysomtee commented
@shawn-hurley Thank you!

2024-02-22 23:30 UTC, Vickysomtee commented
@shawn-hurley 

I think I might need help to get the demo test working but it's not currently the blocker for this PR. I had a little tight schedule but I am free now and I will continue on this. If I still need help on the demo test, I would let you know. Thank you!

2024-03-04 02:19 UTC, Vickysomtee commented
I have updated the PR with the refactor @pranavgaikwad @shawn-hurley

2024-03-04 12:54 UTC, pranavgaikwad commented
@Vickysomtee Thank you. Really appreciate you helping out. Is it ready for review?

2024-03-04 13:05 UTC, pranavgaikwad approved these changes

2024-03-04 13:05 UTC, pranavgaikwad commented on cmd/analyzer/main.go
> +		println(err.Error())
Can we use `os.Exit(1)` here?

2024-03-04 13:05 UTC, pranavgaikwad commented on cmd/analyzer/main.go
> +		PreRun: func(c *cobra.Command, args []string) {
Instead of exiting here, can we use PreRunE function and only return an error?

2024-03-04 13:06 UTC, pranavgaikwad requested changes
Requesting minor changes

2024-03-04 13:22 UTC, pranavgaikwad requested changes
One small request

2024-03-04 13:22 UTC, pranavgaikwad commented on cmd/analyzer/main.go
> +				errLog.Error(err, "failed to validate flags")
nit: can we `return err` here? and return nil after the if block? just making sure if we make changes in future, it doesn't go unnoticed that err could be non-nil after the if block

2024-03-04 13:39 UTC, pranavgaikwad approved these changes
Thank you @Vickysomtee

2024-03-04 13:46 UTC, shawn-hurley approved these changes
Thank you for the refactor! this is looking really good

2024-03-04 14:46 UTC, merged