Update indirect Dependency location
konveyor/analyzer-lsp pull request #557
Opened 2024-03-27 12:57 UTC by aufi

Updating dependency incident location lookup for indirect dependencies to point to "parent" dependency location. E.g. for maven-javax-to-jakarta-00002 rule.

Replaces https://github.com/konveyor/analyzer-lsp/pull/532

Related to https://issues.redhat.com/browse/MTA-2006

2024-03-27 19:52 UTC, pranavgaikwad requested changes
Thank you for the fix, overall looks good. Requesting minor changes

2024-03-27 19:52 UTC, pranavgaikwad commented on rule-example.yaml
> +  customVariables: []
nit: can we shrink this rule, just keep the required fields for brevity i.e. remove labels, links, customVariables?

2024-03-27 19:52 UTC, pranavgaikwad commented on demo-dep-output.yaml
> +        name: ch.qos.logback.logback-classic
nit: can we produce only the required fields of the baseDep

2024-03-27 19:52 UTC, pranavgaikwad commented on provider/provider.go
> +			} else if baseDep, ok := matchedDep.dep.Extras["baseDep"]; ok {
since I looked into too many perf issues recently :)... maybe we can make only one call to GetLocation based on either direct or base dep?

2024-03-28 08:22 UTC, aufi commented
Thanks for review @pranavgaikwad, will update!

2024-03-28 15:49 UTC, pranavgaikwad approved these changes
@aufi Thank you! LGTM

2024-04-02 23:09 UTC, merged