Gradle support
konveyor/analyzer-lsp pull request #591
Opened 2024-04-26 10:16 UTC by jmle

Adds support for fetching dependencies with Gradle projects.

- This implementation assumes that there is a Gradle wrapper included in the project, otherwise it is not possible to know which Gradle version is needed.
- To maximize compatibility with most Gradle versions, JDK8 must be used. There are a number of ways to specify this on newer Gradle versions, but for older versions the only thing that seems to work is setting `JAVA_HOME`.

2024-05-06 12:52 UTC, pranavgaikwad requested changes
small nits / questions...overall looks great!

2024-05-06 12:52 UTC, pranavgaikwad commented on demo-dep-output.yaml
> +    prefix: file://org/yaml/snakeyaml/1.30
what happened to file URIs here?

2024-05-06 12:52 UTC, pranavgaikwad commented on external-providers/java-external-provider/pkg/java_external_provider/dependency.go
> +		f, err := filepath.Abs(filepath.Join(p.config.Location, "build.gradle"))
is Abs() running os.Stat()?

2024-05-06 12:52 UTC, pranavgaikwad commented on external-providers/java-external-provider/pkg/java_external_provider/dependency.go
> +	if p.getBuildTool() == gradle {
is this redundant given that there's a switch in GetDepenenciesDAG()? I think we will need to move fallback call inside GetDepenciesDAG()

2024-05-20 14:01 UTC, jmle commented on external-providers/java-external-provider/pkg/java_external_provider/dependency.go
> +		f, err := filepath.Abs(filepath.Join(p.config.Location, "build.gradle"))
:+1:

2024-05-20 15:19 UTC, jmle commented on demo-dep-output.yaml
> +    prefix: file://org/yaml/snakeyaml/1.30
This should be fixed now

2024-05-23 11:11 UTC, closed without merging

2024-05-23 11:11 UTC, jmle commented
Superseded by https://github.com/konveyor/analyzer-lsp/pull/609