Adding a windup re-written rule and demo
konveyor/analyzer-lsp pull request #63
Opened 2023-01-23 15:15 UTC by shawn-hurley

1. Adding ability to call for mulitple locations
2. Adding new rule demo to prove multiple locations

WAIT for the infra to be published before merging

2023-01-23 15:45 UTC, fabianvf requested changes

2023-01-23 19:41 UTC, shawn-hurley commented on provider/java/filter.go
> +					// TODO(fabianvf) remove this, Temporary for testing purpses
Later, it might be usuful in a message is my thinking.

2023-01-23 19:42 UTC, shawn-hurley commented on provider/java/filter.go
> +		// Verify symbol is method.
+1

2023-01-23 23:41 UTC, shawn-hurley commented on Dockerfile
> +# Uncomment to enable delve debugging
removed

2023-01-23 23:41 UTC, shawn-hurley commented on provider/java/filter.go
> +func (p *javaProvider) filterTypeReferneces(symbols []protocol.WorkspaceSymbol) ([]lib.IncidentContext, error) {
updated

2023-01-23 23:42 UTC, shawn-hurley commented on provider/java/provider.go
> +// func (p *javaProvider) getValues(val interface{}) (string, string, error) {
removed!

2023-01-23 23:42 UTC, shawn-hurley commented on provider/java/provider.go
> +	fmt.Println(params)
removed

2023-01-23 23:44 UTC, shawn-hurley commented on provider/java/provider.go
> +	fmt.Println(wsp)
removed

2023-01-23 23:53 UTC, shawn-hurley commented on provider/builtin/provider.go
> +		} else if len(cond.XML.Filepaths) == 1 {
@pranavgaikwad @fabianvf 

I think we may want to make this documentable somehow, this feels bad with all the go -> yaml -> mustache -> yaml -> go. 

I don't have a solution but something to think about

2023-01-24 13:45 UTC, shawn-hurley commented on provider/builtin/provider.go
> +		} else if len(cond.XML.Filepaths) == 1 {
https://github.com/cbroglie/mustache/issues/83 

Seems there is a way to deal with this, but will still produce invalid JSON.

2023-01-25 16:44 UTC, fabianvf approved these changes

2023-01-25 17:57 UTC, merged